version: '3.9'
services:
  service1:
    build: ./service1
    container_name: service1
    ports:
      - "3001:3000"

  service2:
    build: ./service2
    container_name: service2
    ports:
      - "3002:3000"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
